export const CustomCellTypes = {
  VEHICLE_LOCATION: 'VEHICLE_LOCATION',
  VEHICLE_CATEGORIES: 'VEHICLE_CATEGORIES',
  BOOKING_REGISTRATION_STATUS: 'BOOKING_REGISTRATION_STATUS',
  BOOKING_SOURCE: 'BOOKING_SOURCE',
  BOOKING_TYPE: 'BOOKING_TYPE',
  BOOKING_TRIP_STATUS: 'BOOKING_TRIP_STATUS',
  AVAILABILITY_STATUS: 'AVAILABILITY_STATUS',
  EDIT_AVAILABILITY_STATUS: 'EDIT_AVAILABILITY_STATUS',
  USER_REGISTRATION_STATUS: 'USER_REGISTRATION_STATUS',
  USER_NAME: 'USER_NAME',
  PRICE_DAYS: 'PRICE_DAYS',
  HIGHLIGHT: 'HIGHLIGHT',
  CHIP: 'CHIP',
  PRICE: 'PRICE',
  DATE: 'DATE',
  VEHICLE_CATEGORY_PRICE_EDIT: 'VEHICLE_CATEGORY_PRICE_EDIT',
  PRICING_RULE_NAME: 'PRICING_RULE_NAME',
  PROMO_RESTRICTION: 'PROMO_RESTRICTION',
  PROMO_MARKETS: 'PROMO_MARKETS',
  SEARCH: 'SEARCH',
  PHONE_NUMBER: 'PHONE_NUMBER',
  TODO_ACTIONS: 'TODO_ACTIONS',
  TASK_GUEST_NAME: 'TASK_GUEST_NAME',
};

/**
 * A list of custom cell types that need the default row click to be suppressed
 */
export const CustomCellTypesWithClick = [
  CustomCellTypes.VEHICLE_CATEGORY_PRICE_EDIT,
  CustomCellTypes.EDIT_AVAILABILITY_STATUS,
];

export default {};
